scoreboard:
  enabled: true
  title: "<gradient:#00ffff:#0000ff>Syntri</gradient>"
  animation:
    enabled: false
    style: WAVE
    interval_ticks: 20
  lines:
    - "&fPlayer: &a%syntri_name%"
    - "&fPing: &b%syntri_ping%ms"
    - "&fWorld: &e%syntri_world%"
    - "&fGamemode: &6%syntri_gamemode%"
    - "&fHealth: &c%syntri_health%"
    - "&fOnline: &d%syntri_online%"
    - "&fBackend: &5%syntri_backend%"
    - "&fMax Players: &f%syntri_max_players%"
    - "&eplay.syntri.net"
