tablist:
  enabled: true
  refresh_ticks: 60

  header:
    - "<gradient:#00ffaa:#0055ff>&lSyntri Network</gradient>"
    - "&7Bem-vindo, &a%player_name%"
    - "&7Online: &a%online% &8/&c%max_players%"

  footer:
    - "&fSeu ping: &e%player_ping%ms"
    - "&fSite: &bwww.syntri.com"
    - "&fDiscord: &ddiscord.gg/syntri"
